const products = [
  {
    id: '1',
    title: 'Lenovo',
    description: 'Wireless Mouse',
    price: '119,00 TL',
    image: '../images/lenovomouse.webp',
    stok: 6,
  },
  {
    id: '2',
    title: 'Apple',
    description: 'Iphone 11 128 GB',
    price: '15.499 TL',
    image: '../images/iphone11.webp',
    stok: 8,
  },
  {
    id: '3',
    title: 'Apple',
    description: 'Ipad 9 128 GB',
    price: '6.599 TL',
    image: '../images/ipad9.webp',
    stok: 4,
  },
  {
    id: '4',
    title: 'Xiaomi Mi',
    description: 'Powerbank',
    price: '329 TL',
    image: '../images/powerbank.webp',
    stok: 5,
  },
  {
    id: '5',
    title: 'Apple',
    description: 'Macbook Air 13',
    price: '20.680 TL',
    image: '../images/macbook.webp',
    stok: 9,
  },
  {
    id: '6',
    title: 'Lenovo',
    description: 'Duet 7 Laptop',
    price: '19.399 TL',
    image: '../images/lenovolaptop.webp',
    stok: 10,
  },
  {
    id: '7',
    title: 'Apple',
    description: 'Watch Series 7',
    price: '8.600 TL',
    image: '../images/applewatch.webp',
    stok: 8,
  },
  {
    id: '8',
    title: 'Monster',
    description: 'Abra A7 Laptop',
    price: '18.600 TL',
    image: '../images/monsterlaptop.webp',
    stok: 5,
  },
  {
    id: '9',
    title: 'Sony',
    description: 'Playstation 5 825 GB',
    price: '17.565 TL',
    image: '../images/ps5.webp',
    stok: 7,
  },
  {
    id: '10',
    title: 'Samsung',
    description: 'M7 Series Smart Monitor',
    price: '5.999 TL',
    image: '../images/samsungmoni.webp',
    stok: 3,
  },
  {
    id: '11',
    title: 'Sony',
    description: 'PS5 Dual Sense Controller',
    price: '1.950 TL',
    image: '../images/sonyconsol.webp',
    stok: 8,
  },
  {
    id: '12',
    title: 'Sony',
    description: 'Black Headphones',
    price: '595 TL',
    image: '../images/sonykulaklık.webp',
    stok: 5,
  },
]

export default products
